core/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("dashboard/",include("dashboard.urls",namespace="dashboard")),
    path("dashboard/accounts/",include("accounts.urls",namespace="accounts")),
    path("dashboard/order/",include("orders.urls" ,namespace="orders")),  
    path("dashboard/vendors/",include("vendors.urls",namespace="vendors")),
    path("dashboard/products/",include("products.urls",namespace="products")),
]

vendors/urls.py
from django.urls import path 

from .views import *

app_name="vendors"
urlpatterns=[
   path("",VendorListView.as_view(),name="vendor_list"),
   path("<slug:slug>/",VendorDetailView.as_view(),name="vendor_detail")
]

vendors/models.py
from django.db import models

# Create your models here.

vendors/views.py
from django.shortcuts import render
from django.views import View 


class VendorListView(View):
    def get(self,request):
        return render(request,"vendors/vendor_list.html")

class VendorDetailView(View):
    def get(self,request,slug):
        return render(request,"vendors/vendor_detail.html")
        

vendors/templates/vendors/vendor_list.html
{% extends 'base.html' %}
{% block  title %}Dashboard{% endblock %}
{% load static %}


{% block  content %}
<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Vendor Profile</h2>
        <div>
            <a href="#" class="btn btn-primary"><i class="material-icons md-plus"></i> Create new</a>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row gx-3">
                <div class="col-lg-4 col-md-6 me-auto">
                    <input type="text" placeholder="Search..." class="form-control" />
                </div>
                <div class="col-lg-2 col-6 col-md-3">
                    <select class="form-select">
                        <option>Show 20</option>
                        <option>Show 30</option>
                        <option>Show 40</option>
                        <option>Show all</option>
                    </select>
                </div>
                <div class="col-lg-2 col-6 col-md-3">
                    <select class="form-select">
                        <option>Status: all</option>
                        <option>Active only</option>
                        <option>Disabled</option>
                    </select>
                </div>
            </div>
        </header>
        <!-- card-header end// -->
        <div class="card-body">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4">
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-1.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Mary Sandra</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #409</p>
                                <p>mary90@example.com</p>
                                <a href="{% url 'vendors:vendor_detail' 1 %}" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-2.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Leslie Alexander</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #478</p>
                                <p>leslie@example.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-3.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Leslie Alexander</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #478</p>
                                <p>leslie@example.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-4.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Floyd Miles</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #171</p>
                                <p>fedor12@example.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-1.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">John Alexander</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #987</p>
                                <p>john@mymail.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-3.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Albert Flores</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #478</p>
                                <p>leslie@example.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-4.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Leslie Alexander</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #478</p>
                                <p>leslie@example.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
                <div class="col">
                    <div class="card card-user">
                        <div class="card-header">
                            <img class="img-md img-avatar" src="{% static 'assets/imgs/people/avatar-1.png' %}" alt="User pic" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mt-50">Marx Alberto</h5>
                            <div class="card-text text-muted">
                                <p class="m-0">Seller ID: #478</p>
                                <p>leslie@example.com</p>
                                <a href="#" class="btn btn-sm btn-brand rounded font-sm mt-15">View details</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- col.// -->
            </div>
            <!-- row.// -->
        </div>
        <!-- card-body end// -->
    </div>
    <!-- card end// -->
    <div class="pagination-area mt-15 mb-50">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-start">
                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                <li class="page-item"><a class="page-link" href="#">02</a></li>
                <li class="page-item"><a class="page-link" href="#">03</a></li>
                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                <li class="page-item"><a class="page-link" href="#">16</a></li>
                <li class="page-item">
                    <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                </li>
            </ul>
        </nav>
    </div>
</section>
{% endblock %}