accounts/urls.py
from django.urls import path 

from .views import *

app_name="accounts"

urlpatterns=[
    path("financial-year/",FinancialYearView.as_view(),name="financial-year"),
    path("sub-accounts/",SubAccountView.as_view(),name="sub-account"),
    path("predifiend-accounts/",PredifiendAccountView.as_view(),name="predifind-account"),
    path("credit-voucher/",CrebitVoucherView.as_view(),name="credit-voucher"),
    path("debit-voucher/",DebitVoucherView.as_view(),name="debit-voucher"),
    path("contra-voucher/",ContraView.as_view(),name="contra-voucher"),
    path("opening-balance/",OpeningBalanceView.as_view(),name="opening-balance"),
    path("journal-voucher/",JournalVoucherView.as_view(),name="journal-voucher"),
    path("chart-of-accounts/",ChartOfAccountView.as_view(),name="chart-of-account"),
    path("bank-reconcilation/",BankReconcilationView.as_view(),name="bank-reconcilation"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include 

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path("dashboard/",include("dashboard.urls",namespace="dashboard")),
    path("dashboard/accounts/",include("accounts.urls",namespace="accounts")),
    path("dashboard/order/",include("orders.urls" ,namespace="orders")),  
    path("dashboard/vendors/",include("vendors.urls",namespace="vendors")),
    path("dashboard/products/",include("products.urls",namespace="products")),
]

dashboard/urls.py
from django.urls import path 

from .views import *

app_name="dashboard"

urlpatterns=[
    path("",DashBoardView.as_view(),name="dashboard"),
    path("add-banner-view/",AddBannerAreaView.as_view(),name="add-banner-view"),
    path("about-us/",AboutUsView.as_view(),name="about-us"),
    path("advertisment/",AdvertismentView.as_view(),name="advertisment"),
    path("bid-settings/",BidSettingView.as_view(),name="bid-settings"),
    path("home-page-section/",HomePageSectionView.as_view(),name="home-page-section"),
    path("language-setting/",LanguageSettingView.as_view(),name="language-setting"),
    path("manage-cupon/",ManageCuponView.as_view(),name="manage-cupon"),
    path("payment-gateway/",PaymentGatwayView.as_view(),name="payment-gateway"),
    path("privacy-policy/",PrivacyPolicyView.as_view(),name="privacy-policy"),
    path("product-review/",ProductReviewView.as_view(),name="product-review"),
    path("quality-setting/",QualitySettingView.as_view(),name="quality-setting"),
    path("seo-setting/",SEOSettingView.as_view(),name="seo-setting"),
    path("shipping-method/",ShippingMethodView.as_view(),name="shipping-method"),
    path("slider-setting/",SliderSettingView.as_view(),name="slider-setting"),
    path("sms-config/",SMSConfigView.as_view(),name="sms-config"),
    path("social-media/",SocialMediaView.as_view(),name="social-media"),
    path("subscriber/",SubscriberView.as_view(),name="subscriber") 
    
]

templates/base.html
<!doctype html>
<html lang="en">
<!--<html lang="ar" dir="rtl">-->
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
    <meta name="author" content="Bdtask">
    <title>Bhulua - {% block title %}{% endblock %}</title>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'assets/dist/img/favicon.png' %}">
    <!--Global Styles(used by all pages)-->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--<link href="assets/plugins/bootstrap/css/bootstrap.rtl.min.css" rel="stylesheet" type="text/css"/>-->
    <link href="{% static 'assets/plugins/metisMenu/metisMenu.css' %}" rel="stylesheet">
    <!--<link href="assets/plugins/metisMenu/metisMenu-rtl.css" rel="stylesheet">-->
    <link href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/typicons/src/typicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/plugins/themify-icons/themify-icons.min.css' %}" rel="stylesheet">
    <!--Third party Styles(used by this page)-->
    
    <link href="{% static 'assets/dist/css/black-gray.css' %}" rel="stylesheet">

    <!--Style Switcher-->
    <link rel="alternate stylesheet" type="text/css" title="black-gray" href="{% static 'assets/dist/css/black-gray.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="green-teal" href="{% static 'assets/dist/css/green-teal.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="gradient-purple" href="{% static 'assets/dist/css/gradient-purple.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="red-pink" href="{% static 'assets/dist/css/red-pink.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="indigo-blue" href="{% static 'assets/dist/css/style-new.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="deep-purple" href="{% static 'assets/dist/css/deep-purple.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="teal" href="{% static 'assets/dist/css/teal.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="pink" href="{% static 'assets/dist/css/pink.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="brown" href="{% static 'assets/dist/css/brown.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="olive" href="{% static 'assets/dist/css/olive.css' %}" />

    {% block css %}{% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/dist/css/styleswitcher.css' %}" />
    <!--<link href="assets/dist/css/style.rtl.css" rel="stylesheet">-->
</head>

<body class="fixed sidebar-mini">
    <!-- Style Switcher Starts -->
    <div id="switcher" class="">
        <div class="content-switcher">
            <h4>STYLE SWITCHER</h4>
            <ul>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('black-gray');" title="Black gray" class="black-gray"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('green-teal');" title="Green teal" class="green-teal"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('gradient-purple');" title="Gradient purple" class="gradient-purple"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('red-pink');" title="Red pink" class="red-pink"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('indigo-blue');" title="Indigo blue" class="indigo-blue"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('deep-purple');" title="Deep purple" class="deep-purple"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('teal');" title="Teal" class="teal"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('pink');" title="Pink" class="pink"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('brown');" title="Brown" class="brown"></a>
                </li>
                <li>
                    <a href="#" onclick="setActiveStyleSheet('olive');" title="Olive" class="olive"></a>
                </li>

            </ul>

            <div id="hideSwitcher">&times;</div>
        </div>
    </div>
    <div id="showSwitcher" class="styleSecondColor"><i class="fa fa-cog fa-spin"></i></div>
    <!-- Style Switcher Ends -->
   {% include 'header.html' %}
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-green">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>

    <!-- #END# Page Loader -->
    <div class="wrapper">
        <!-- Sidebar  -->
        {% include 'sidebar.html' %}
        <!-- Page Content  -->
        {% block content %}{% endblock %}
        <!--/.wrapper-->
    </div>
    <!--Global script(used by all pages)-->
    <script src="{% static 'assets/plugins/jQuery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/plugins/metisMenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'assets/plugins/perfect-scrollbar/dist/perfect-scrollbar.min.js' %}"></script>
    <!-- Third Party Scripts(used by this page)-->
    {% block js %}{% endblock %}
    <!--Page Active Scripts(used by this page)-->
    
    <!--Page Scripts(used by all page)-->
    <script src="{% static 'assets/dist/js/sidebar.js' %}"></script>
    <script src="{% static 'assets/dist/js/styleswitcher.js' %}"></script>

 
</body>

</html>

templates/footer.html
{% load static %}
<footer class="footer-content">
    <div class="footer-text d-flex align-items-center justify-content-between">
        <div class="copy">© 2018 Bdtask Responsive Bootstrap 4 Dashboard Template</div>
        <div class="credit">Designed by: <a href="#">Bdtask</a></div>
    </div>
</footer>

templates/header.html
{% load static %}
<nav class="navbar-custom-menu navbar navbar-expand-xl m-0">
    <div class="sidebar-toggle-icon" id="sidebarCollapse">
        sidebar toggle<span></span>
    </div>
    <!--/.sidebar toggle icon-->
    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Toggler -->
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbar-collapse" aria-expanded="true" aria-label="Toggle navigation"><span></span> <span></span></button>
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#"><i class="typcn typcn-social-dribbble top-menu-icon"></i>Buyer's & Style <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="typcn typcn-point-of-interest-outline top-menu-icon"></i>Management</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle material-ripple" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="typcn typcn-weather-stormy top-menu-icon"></i>Salary Rule
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Salary Break Down</a></li>
                    <li><a class="dropdown-item" href="#">Salary Head</a></li>
                    <li><a class="dropdown-item" href="#">Bonus Types</a></li>
                    <li><a class="dropdown-item" href="#">Bonus Allocation</a></li>
                    <li><a class="dropdown-item" href="#">Bonus Rule</a></li>
                    <li><a class="dropdown-item" href="#">Bonus Stamp Charge</a></li>
                    <li><a class="dropdown-item" href="#">OverTime Setting</a></li>
                    <li><a class="dropdown-item" href="#">Absent Planing</a></li>
                    <li><a class="dropdown-item" href="#">Salary Head Planning</a></li>
                    <li><a class="dropdown-item" href="#">Salary Benefits</a></li>
                    <li><a class="dropdown-item" href="#">Spot Award</a></li>
                    <li><a class="dropdown-item" href="#">Salary Payment Mode</a></li>
                    <li><a class="dropdown-item" href="#">Attendances Late Planning</a></li>
                    <li><a class="dropdown-item" href="#">Salary Planning</a></li>
                    <li><a class="dropdown-item" href="#">Holiday Allowance Settings</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">
                    <i class="typcn typcn-leaf top-menu-icon"></i>Account Manager
                </a>
            </li>
        </ul>
    </div>
    <div class="navbar-icon d-flex">
        <ul class="navbar-nav flex-row align-items-center">
            <li class="nav-item dropdown quick-actions">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="typcn typcn-th-large-outline"></i>
                </a>
                <div class="dropdown-menu">
                    <div class="nav-grid-row row">
                        <a href="#" class="icon-menu-item col-4">
                            <i class="typcn typcn-cog-outline d-block"></i>
                            <span>Settings</span>
                        </a>
                        <a href="#" class="icon-menu-item col-4">
                            <i class="typcn typcn-group-outline d-block"></i>
                            <span>Users</span>
                        </a>
                        <a href="#" class="icon-menu-item col-4">
                            <i class="typcn typcn-puzzle-outline d-block"></i>
                            <span>Components</span>
                        </a>
                        <a href="#" class="icon-menu-item col-4">
                            <i class="typcn typcn-chart-bar-outline d-block"></i>
                            <span>Profits</span>
                        </a>
                        <a href="#" class="icon-menu-item col-4">
                            <i class="typcn typcn-time d-block"></i>
                            <span>New Event</span>
                        </a>
                        <a href="#" class="icon-menu-item col-4">
                            <i class="typcn typcn-edit d-block"></i>
                            <span>Tasks</span>
                        </a>
                    </div>
                </div>
            </li>
            <!--/.dropdown-->
            <li class="nav-item">
                <a class="nav-link" href="#" id="btnFullscreen"><i class="full-screen_icon typcn typcn-arrow-move-outline"></i></a>
            </li>
            <li class="nav-item dropdown notification">
                <a class="nav-link dropdown-toggle badge-dot" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="typcn typcn-bell"></i>
                </a>
                <div class="dropdown-menu">
                    <h6 class="notification-title">Notifications</h6>
                    <p class="notification-text text-muted">You have 2 unread notification</p>
                    <div class="notification-list">
                        <a href="#" class="notification text-reset d-flex new">
                            <div class="img-user flex-shrink-0"><img src="assets/dist/img/avatar.png" alt=""></div>
                            <div class="notification-body">
                                <h6>Congratulate <strong>Socrates Itumay</strong> for work anniversaries</h6>
                                <span class="text-muted"><i class="me-1 fst-normal" role="img" aria-label="Emoji">💬</i> Just Now</span>
                            </div>
                        </a>
                        <!--/.media -->
                        <a href="#" class="notification text-reset d-flex new">
                            <div class="img-user flex-shrink-0 online"><img src="assets/dist/img/avatar2.png" alt=""></div>
                            <div class="notification-body">
                                <h6><strong>Joyce Chua</strong> replied to your comment : "Hello world 😍"</h6>
                                <span class="text-muted">Mar 13 04:16am</span>
                            </div>
                        </a>
                        <!--/.media -->
                        <a href="#" class="notification text-reset d-flex d-grid">
                            <div class="img-user flex-shrink-0"><img src="assets/dist/img/avatar3.png" alt=""></div>
                            <div class="notification-body">
                                <div class="h6"><strong>Althea Cabardo</strong> commented
                                    <blockquote class="mb-0">“I don’t think this really makes sense to do without approval from Johnathan since he’s the one...” </blockquote>
                                </div>
                                <span class="text-muted">Mar 13 02:56am</span>
                            </div>
                        </a>
                        <!--/.media -->
                        <a href="#" class="notification text-reset d-flex">
                            <div class="img-user flex-shrink-0"><img src="assets/dist/img/avatar4.png" alt=""></div>
                            <div class="notification-body">
                                <h6><strong>Adrian Monino</strong> added new comment on your photo <span class="badge bg-success">Review</span></h6>
                                <span class="text-muted">Mar 12 10:40pm</span>
                            </div>
                        </a>
                        <!--/.media -->
                    </div>
                    <!--/.notification -->
                    <div class="dropdown-footer"><a href="">View All Notifications</a></div>
                </div>
                <!--/.dropdown-menu -->
            </li>
            <!--/.dropdown-->
            <li class="nav-item dropdown user-menu">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <!--<img src="assets/dist/img/user2-160x160.png" alt="">-->
                    <i class="typcn typcn-user-add-outline"></i>
                </a>
                <div class="dropdown-menu">
                    <div class="dropdown-header d-sm-none">
                        <a href="" class="header-arrow"><i class="icon ion-md-arrow-back"></i></a>
                    </div>
                    <div class="user-header">
                        <div class="img-user">
                            <img src="assets/dist/img/avatar-1.jpg" alt="">
                        </div>
                        <!-- img-user -->
                        <h6>Naeem Khan</h6>
                        <span>example@gmail.com</span>
                    </div>
                    <!-- user-header -->
                    <a href="" class="dropdown-item"><i class="typcn typcn-user-outline"></i> My Profile</a>
                    <a href="" class="dropdown-item"><i class="typcn typcn-edit"></i> Edit Profile</a>
                    <a href="" class="dropdown-item"><i class="typcn typcn-arrow-shuffle"></i> Activity Logs</a>
                    <a href="" class="dropdown-item"><i class="typcn typcn-cog-outline"></i> Account Settings</a>
                    <a href="page-signin.html" class="dropdown-item"><i class="typcn typcn-key-outline"></i> Sign Out</a>
                </div>
                <!--/.dropdown-menu -->
            </li>
        </ul>
        <!--/.navbar nav-->
        <div class="nav-clock">
            <div class="time">
                <span class="time-hours"></span>
                <span class="time-min"></span>
                <span class="time-sec"></span>
            </div>
        </div>
        <!-- nav-clock -->
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="typcn typcn-th-menu-outline"></i>
        </button>
</nav>

templates/sidebar.html
{% load static %}
<nav class="sidebar sidebar-bunker" style="overflow-y: auto;">
    <div class="sidebar-header">
        <a href="index.html" class="sidebar-brand">
            <img class="sidebar-brand_icon" src="https://www.bdtask.com/asset/img/bdtask-logo.webp" alt="">

        </a>
    </div>
    <!--/.sidebar header-->
    <div class="profile-element d-flex align-items-center flex-shrink-0">
        <div class="avatar online">
            <img src="{% static 'assets/dist/img/man6.png' %}" class="img-fluid rounded-circle" alt="">
        </div>
        <div class="profile-text">
            <h6 class="m-0">Naeem Khan</h6>
            <span>example@gmail.com</span>
        </div>
    </div>
    <!--/.profile element-->
    <form class="search sidebar-form" action="#" method="get">
        <div class="search__inner">
            <input type="text" class="search__text" placeholder="Search...">
            <i class="typcn typcn-zoom-outline search__helper" data-sa-action="search-close"></i>
        </div>
    </form>
    <!--/.search-->
    <div class="sidebar-body">
        <nav class="sidebar-nav">
            <ul class="metismenu">
                <li class="nav-label">
                    <span class="nav-label_text">Main Menu</span>
                    <small class="ti-more-alt nav-label_ellipsis"></small>
                </li>
                
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="typcn typcn-home-outline"></i> Dashboard
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Default</a></li>
                        <li><a href="dashboard_two.html">Dashboard Two</a></li>
                    </ul>
                </li>
               
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fab fa-product-hunt"></i> Category
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Add category</a></li>
                        <li><a href="dashboard_two.html">category List</a></li>
                      
                    </ul>
                </li>
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fab fa-product-hunt"></i> Products
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Add Products</a></li>
                        <li><a href="dashboard_two.html">Product List</a></li>
                        <li><a href="dashboard_two.html">Reviews</a></li>
                        <li><a href="dashboard_two.html">Categories</a></li>
                    </ul>
                </li>

                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fas fa-user-clock"></i>Vendors
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Vendor List</a></li>
                       
                    </ul>
                </li>
               
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fas fa-user-clock"></i>Customers
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Customer List</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fas fa-comment-dots"></i> Bids
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Bids List</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fas fa-money-check"></i>  Marchants
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Marchants List</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fas fa-hand-holding-usd"></i> Sales
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Sales List</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="fa fa-truck" aria-hidden="true"></i> Delivery
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Delivery List</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="typcn typcn-home-outline"></i> Reports
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="index.html">Sale Reports</a></li>
                        <li><a href="index.html">Bids Reports</a></li>
                       
                    </ul>
                </li>
              

                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="typcn typcn-home-outline"></i> Settings
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="{% url 'dashboard:slider-setting'%}">Slider Settings</a></li>
                        <li><a href="{% url 'dashboard:advertisment'%}">Advertisement</a></li>
                        <li><a href="{% url 'dashboard:add-banner-view'%}">Add Banner Area</a></li>
                        <li><a href="{% url 'dashboard:home-page-section'%}">Home Page Section</a></li>
                        <li><a href="{% url 'dashboard:product-review'%}">Product Review</a></li>
                        <li><a href="{% url 'dashboard:subscriber'%}">Subscriber</a></li>
                        <li><a href="{% url 'dashboard:bid-settings'%}">Bid Settings</a></li>
                        <li><a href="{% url 'dashboard:quality-setting'%}">Quanlity Settings(OCR)</a></li>
                        <li><a href="{% url 'dashboard:shipping-method'%}">Shipping Method</a></li>
                        <li><a href="{% url 'dashboard:seo-setting'%}">SEO Settings</a></li>
                        <li><a href="{% url 'dashboard:social-media'%}">Social Media</a></li>
                        <li><a href="{% url 'dashboard:about-us'%}">About Us</a></li>
                        <li><a href="{% url 'dashboard:privacy-policy'%}">Privacy Policy</a></li>
                        <li><a href="{% url 'dashboard:language-setting'%}">Language Settings</a></li>
                        <li><a href="{% url 'dashboard:sms-config'%}">SMS Configurations</a></li>
                        <li><a href="{% url 'dashboard:payment-gateway'%}">Payment Gateway</a></li>
                        <li><a href="{% url 'dashboard:manage-cupon'%}">Manage Cupon</a></li>
                      
                       
                    </ul>
                </li>

                <li>
                    <a class="has-arrow material-ripple" href="#">
                        <i class="hvr-buzz-out fas fa-user-lock"></i>Accounts
                    </a>
                    <ul class="nav-second-level">
                        <li><a href="{% url 'accounts:financial-year' %}">Financial year</a></li>
                        <li><a href="{% url 'accounts:chart-of-account' %}">Chart of Accounts</a></li>
                        <li><a href="{% url 'accounts:sub-account' %}">Sub Accounts</a></li>
                        <li><a href="{% url 'accounts:predifind-account' %}">Predifined Account</a></li>
                        <li><a href="{% url 'accounts:opening-balance' %}">Opening Balance</a></li>
                        <li><a href="{% url 'accounts:debit-voucher' %}">Debit Voucher</a></li>
                        <li><a href="{% url 'accounts:credit-voucher' %}">Credit Voucher</a></li>
                        <li><a href="{% url 'accounts:contra-voucher' %}">Contra Voucher</a></li>
                        <li><a href="{% url 'accounts:journal-voucher' %}">Journal Voucher</a></li>
                        <li><a href="{% url 'accounts:bank-reconcilation' %}">Bank Reconcilation</a></li>
                        <li><a href="{% url 'accounts:sub-account' %}">Voucher Approval</a></li>
                        <li>  
                        <a class="has-arrow material-ripple" href="#" style="color:white;background: rgba(0, 0, 0, 0.755);">
                            <i class="typcn typcn-home-outline"></i> Accounts Reports
                        </a>
                        <ul class="nav-second-level" style="margin-left:30px; color:black">
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);">Cashbook</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">Bank Book</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">City Bank</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">General Ledger</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">Sub Ledger</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">Profit Loss</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">Trial Balance</a></li>
                            <li><a href="index.html" style="color:rgba(0, 0, 0, 0.755);;">Balance Sheet</a></li>
                           
                           
                        </ul>
                    
                    </li>
                    
                       
                    </ul>
                </li>
                <li>
                    <a href="chat.html"><i class="typcn typcn-messages"></i> Profiles</a>
                </li>  
                 
               
               
              
            </ul>
        </nav>
    </div>
    <!-- sidebar-body -->
</nav>